export const meta = {
  name: 'amaze-gauntlet',
  description: 'A-MAZE quality gauntlet: score every module 0-10 vs top-tier web arcade games; failing builders auto-revise up to 4 rounds; final dimensional stress gate',
  whenToUse: 'After any substantive change to src/, to re-score modules and drive them to >= 8.5. args: {only?: string[], maxRounds?: number}',
  phases: [
    { title: 'Evidence', detail: 'tests, maze validation, stress, headless verify + screenshots' },
    { title: 'Critique', detail: 'one critic per module' },
    { title: 'Revise', detail: 'builders fix failing modules from structured critique' },
    { title: 'Integrate', detail: 'integrator re-verifies seams + commits' },
    { title: 'Stress Gate', detail: 'extreme grid scales, soak, leak + frame-drop check' },
    { title: 'Status', detail: 'write docs/STATUS.json' },
  ],
}

const ROOT = 'C:/Users/gotmi/Documents/GitHub/a-maze'
const MAX_ROUNDS = args?.maxRounds ?? 4
const THRESH = 8.5

const SCORE = {
  type: 'object',
  properties: {
    module: { type: 'string' },
    score: { type: 'number' },
    errors: { type: 'number', description: 'console/page/test errors attributable to this module' },
    pass: { type: 'boolean' },
    strengths: { type: 'array', items: { type: 'string' } },
    issues: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['blocker', 'high', 'medium', 'low'] }, file: { type: 'string' }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'issue', 'fix'] } },
    verdict: { type: 'string' },
  },
  required: ['module', 'score', 'errors', 'pass', 'strengths', 'issues', 'verdict'],
}
const FIX = {
  type: 'object',
  properties: { module: { type: 'string' }, changed: { type: 'array', items: { type: 'string' } }, addressed: { type: 'array', items: { type: 'string' } }, notAddressed: { type: 'array', items: { type: 'string' } }, selfScore: { type: 'number' } },
  required: ['module', 'changed', 'addressed', 'notAddressed', 'selfScore'],
}
const EVIDENCE = { type: 'object', properties: { summary: { type: 'string' }, allPass: { type: 'boolean' } }, required: ['summary', 'allPass'] }

const RUBRIC = `SCORING RUBRIC (0-10). Benchmark = top-tier web/indie arcade & retro dungeon crawlers: Labyrinth: The Wizard's Cat (the art reference docs/art-reference.png), Wolfenstein 3D / Doom browser ports, the best js13kGames raycasters, Krunker's responsiveness. 10 = flawless; 9 = excellent, tiny nits; 8.5 = premium indie release quality; 7 = solid but unpolished or one real flaw; 5 = programmer art / clunky / confusing; 3 = broken in places; 0 = unusable. PASS requires score >= ${THRESH} AND zero errors attributable to the module AND no blocker/high issue. NEVER inflate — you are adversarial. Every issue must name the file (and line/function/number) and a concrete fix. Engineering bar for every module: // @ts-check + JSDoc types on all exports, comments that explain why, no allocations in per-frame/per-step hot paths, no leaks (listeners/nodes/timers cleaned up), graceful failure, contract in ARCHITECTURE.md honoured, module isolation (allowed-import table) honoured, meaningful node:test coverage. If you cannot verify something, say so and score what you saw.`

const evidencePrompt = `Root ${ROOT}. Dev server at http://localhost:5173 (if curl fails, start \`node tools/serve.mjs\` in background). Do not modify source. Run, capturing output: \`npm test\`, \`node tools/validate-mazes.mjs\`, \`node tools/stress.mjs\`, \`node tools/verify.mjs --tag gauntlet\`. Then return a compact summary: each command pass/fail with failing test names and first 5 error texts; validate totals (mazes checked, failures, ms); stress numbers (largest grid, ms, heap); verify JSON essentials (pass, failReasons, fps, render ms avg/p99, heap growth, console errors/warnings, phases reached, screenshot file paths). allPass = every command passed.`

const view = (files) => `Read the relevant code: ${files}. Also read ARCHITECTURE.md.`
const critics = (ev) => ({
  renderer: `You are an ART DIRECTOR + graphics engineer critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/renderer/. ${view('all of src/renderer/')} READ the gauntlet screenshots listed in the evidence (logs/shot-gauntlet-*.png) and docs/art-reference.png with the Read tool, and also screenshot src/renderer/preview.html yourself at 1280x720 with a puppeteer-core scratch script (Chrome at C:/Program Files/Google/Chrome/Application/chrome.exe) and READ those PNGs. Judge: does it look like the reference (stone block walls w/ moss & vines, cobbles, wooden ceiling, torches, warm/cool lighting) or like programmer art? texture quality & palette cohesion, crisp pixel scaling (no blur, no shimmering), lighting/fog mood, sprite quality (gems, oil, portal, torch flames), fisheye/texture-mapping correctness, perf (render ms from evidence, per-frame allocations in code), post effects taste. The project lead reviewed logs/shot-integ-play.png and flagged three suspicions to test explicitly (confirm or refute with evidence, do not take on faith): (1) wall texture reads as tall flat blue-grey panels, not the reference's chunky stone BLOCKS with dark mortar courses and bevelled highlights — block size/aspect and mortar contrast may be wrong at typical corridor distance; (2) lighting is flat and uniformly cool — the reference has a warm orange torch pool close to the camera falling off into cool blue shadow, and visible wall torches; are wall torches actually spawning and visible in play, and is the player torch warm enough?; (3) the corridor reads taller than the reference's roughly square proportion — check wall height/FOV/projection constants. Score module 'renderer'.\n\nEvidence:\n${ev}`,
  ui: `You are a UI/UX + retro game art critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/ui/ (font.js, hud.js, menus.js, format.js; NOT audio.js). ${view('src/ui/*.js except audio.js, src/main.js wiring of hud/menus')} READ the gauntlet screenshots (title, play, minimap, level complete, game over, mobile) and docs/art-reference.png with the Read tool; screenshot src/ui/preview.html?screen=title|hud|pause|options|complete|gameover|loading yourself at 1280x720 and 390x844 with puppeteer-core (Chrome at C:/Program Files/Google/Chrome/Application/chrome.exe) and READ them. Judge: pixel-font legibility and charm (gold gothic title like the reference?), hierarchy, HUD readability without clutter, minimap usefulness, menu navigation by keyboard AND mouse AND touch (drive it in puppeteer on the real game at / : press arrows/Enter, click items), tally animation feel, mobile layout, consistency with world art, reduced-motion. Score module 'ui'.\n\nEvidence:\n${ev}`,
  state: `You are a GAME FEEL + systems critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/state/ (store, game reducer, sim, balance, save). ${view('all of src/state/')} Write a scratchpad Node script in logs/ that imports src/state and src/maze to: build level 1..12 and simulate an autopilot following validation.path at 60Hz measuring time-to-exit vs fuel budget (is every level beatable with margin? is L1 generous and L10 tense?); fire the player into walls at many angles/speeds/dt (incl. dt=0.25) and corners and assert no tunnelling/NaN; verify pickups, score formulas vs ARCHITECTURE section 1, lowFuel once, gameOver + best, phase machine rejects invalid actions, per-step allocation check (run 100k ticks, compare heap). Judge feel constants (accel, speed, turn, bob) against Wolfenstein/Doom-like responsiveness, pacing/difficulty curve, attract-mode camera smoothness, determinism, save robustness. Score module 'state'.\n\nEvidence:\n${ev}`,
  maze: `You are an ALGORITHMS critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/maze/ + tools/validate-mazes.mjs + tools/stress.mjs. ${view('all of src/maze/, tools/validate-mazes.mjs, tools/stress.mjs')} Independently verify the solvability guarantee: write your OWN scratchpad checker in logs/ (do not reuse validator.js) that flood-fills tiles and checks start→exit reachability, full connectivity, sealed borders and perfect-maze edge count for braid 0 across >= 5000 random seeds and odd sizes (1x1, 1xN, Nx1, primes, 300x7), and compare against validator.js output for every maze (any disagreement is a blocker). Check determinism, worker + client fallback/timeout logic (read carefully: stale ids, error path, transfer), populate placement quality (items reachable, on floor, spread, fuel budget formula sane), maze aesthetics for play (corridor texture, long enough solution, not trivially short; braid gives loops at higher levels), time/memory at 2000x2000 from evidence, no recursion anywhere. Score module 'maze'.\n\nEvidence:\n${ev}`,
  input: `You are an INPUT/CONTROLS critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/input/. ${view('all of src/input/ and how src/main.js uses it')} Drive the real game in puppeteer-core (Chrome at C:/Program Files/Google/Chrome/Application/chrome.exe, http://localhost:5173/?headless=1): keyboard WASD/arrows/Shift/M/Esc/Enter through menus and gameplay (check state via window.__game.state()), check held-key release on blur, emulate touch (page.emulate a phone with hasTouch, dispatch touch events on the left stick zone and right look zone, tap the pause button) and verify movement/turning/pause; read code for pointer lock handling, movementX spike clamping, gamepad deadzone math, listener cleanup in destroy(), no per-poll allocation. Judge latency/responsiveness and completeness vs a polished browser FPS. Score module 'input'.\n\nEvidence:\n${ev}`,
  audio: `You are an AUDIO DESIGN critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/ui/audio.js. ${view('src/ui/audio.js, src/ui/audio.test.mjs, and how src/main.js routes events')} You cannot hear, so evaluate by (a) reading synthesis code for musicality/design quality (envelopes without clicks, filter sweeps, detune, sensible frequencies, variation to avoid repetition fatigue, mix levels/headroom via compressor), (b) instrumenting in puppeteer-core (Chrome at C:/Program Files/Google/Chrome/Application/chrome.exe, launch with --autoplay-policy=no-user-gesture-required): load the game, play via __game input inject, and count live AudioNodes over a 30s soak by monkey-patching AudioContext.prototype create* methods and 'ended' handlers to confirm no node leaks and voice limiting; confirm no exceptions when AudioContext is undefined. Check every GameEvent type is handled, lookahead scheduling for music, suspend on hidden. Score module 'audio'.\n\nEvidence:\n${ev}`,
  core: `You are a CODE-QUALITY + runtime critic for "A-MAZE" (${ROOT}). ${RUBRIC}\nModule: src/core/ + src/main.js + index.html + styles.css (integration shell). ${view('all of src/core/, src/main.js, index.html, styles.css, tools/verify.mjs')} Judge: fixed-timestep loop correctness (spiral-of-death clamp, hidden-tab pause, interpolation alpha), FrameStats allocation-free, rng quality & determinism, main.js boot robustness (fatal error panel, stale maze build tokens, resize/DPR handling, pointer lock flow, auto-pause on blur, persistence), unidirectional data flow actually enforced (grep for writes to state outside src/state), allowed-import table honoured (grep every import), leak freedom (listeners/rAF/worker disposal), verify.mjs gates meaningful (fps/render/heap/errors) and results from evidence. Load the page in puppeteer-core at 1280x720 and 390x844 and also with ?debug=1; throttle CPU 4x via CDP Emulation.setCPUThrottlingRate and report fps/frame drops. Score module 'core'.\n\nEvidence:\n${ev}`,
})
const FOLDER = { renderer: 'src/renderer/', ui: 'src/ui/ (except audio.js)', state: 'src/state/', maze: 'src/maze/ + tools/validate-mazes.mjs + tools/stress.mjs', input: 'src/input/', audio: 'src/ui/audio.js (+ audio.test.mjs)', core: 'src/core/ + src/main.js + index.html + styles.css + tools/verify.mjs (you are the integrator for core)' }
const EFFORT = { renderer: 'xhigh', ui: 'xhigh', state: 'high', maze: 'high', input: 'high', audio: 'high', core: 'high' }

phase('Evidence')
let evidence = await agent(evidencePrompt, { label: 'evidence', phase: 'Evidence', schema: EVIDENCE, effort: 'low' })

const scores = {}
const history = []
const only = Array.isArray(args?.only) && args.only.length ? new Set(args.only) : null
for (let round = 1; round <= MAX_ROUNDS; round++) {
  phase('Critique')
  const cp = critics(evidence?.summary || 'evidence agent failed — gather your own evidence')
  const names = Object.keys(cp).filter((m) => !scores[m]?.passed && (!only || only.has(m)))
  if (!names.length) break
  // From round 3 on, anchor each critic to the previous round's findings so scoring converges:
  // verify those first, and only add new issues that materially change the player experience.
  const anchor = (m) => round >= 3 && scores[m] ? `\n\nPREVIOUS ROUND (${scores[m].round}) scored this module ${scores[m].score}/10 with these issues; a builder has since revised it:\n${scores[m].issues.map((i) => `- [${i.severity}] ${i.file} | ${i.issue.slice(0, 400)}`).join('\n')}\nFIRST verify each one against the current tree (fixed / partly / not fixed) and weigh your score mainly on that. Do NOT re-litigate settled design decisions or promote nits to high. Add a NEW issue only if a player would notice it or it is a real defect; new findings that are merely stylistic belong at low severity. A module whose previous high issues are verifiably fixed and that has no new player-visible defects should score >= ${THRESH}.` : ''
  const results = (await parallel(names.map((m) => () => agent(cp[m] + anchor(m), { label: `critic:${m}:r${round}`, phase: 'Critique', schema: SCORE, effort: EFFORT[m] })))).filter(Boolean)
  for (const r of results) {
    const passed = r.score >= THRESH && r.errors === 0 && !r.issues.some((i) => i.severity === 'blocker' || i.severity === 'high')
    scores[r.module] = { ...r, passed, round }
  }
  const failing = results.filter((r) => !scores[r.module].passed)
  history.push({ round, scores: Object.fromEntries(results.map((r) => [r.module, r.score])) })
  log(`Round ${round}: ${results.map((r) => `${r.module}=${r.score}${scores[r.module].passed ? '✓' : '✗'}`).join(' ')}`)
  if (!failing.length || round === MAX_ROUNDS) break

  phase('Revise')
  const fixes = await parallel(failing.map((f) => () => agent(`You are the builder that owns ${FOLDER[f.module]} in "A-MAZE" (${ROOT}; plain ES modules; dev server http://localhost:5173 — keep it running). Read ARCHITECTURE.md, CLAUDE.md, docs/STATUS.json, and all of your folder. An adversarial critic scored your module ${f.score}/10 in round ${round} (PASS needs >= ${THRESH}, zero attributable errors, no blocker/high issues).\nVerdict: ${f.verdict}\nStructured critique (severity | file | issue → fix):\n${f.issues.map((i) => `- [${i.severity}] ${i.file} | ${i.issue} → ${i.fix}`).join('\n')}\nStrengths to preserve: ${f.strengths.join('; ')}\nRules: edit ONLY your folder; honour ARCHITECTURE.md contracts (if a contract change is truly required, do the minimal version and list it in notAddressed as "CONTRACT:" so the integrator handles it); // @ts-check + JSDoc; no placeholders. Fix EVERY blocker/high/medium issue, then lows where cheap. After changes run \`npm test\` and \`node tools/verify.mjs --tag fix-${f.module}\`${f.module === 'maze' ? ', `node tools/validate-mazes.mjs` and `node tools/stress.mjs`' : ''} and READ the output${['renderer', 'ui'].includes(f.module) ? ' and the screenshots (Read the PNGs and compare with docs/art-reference.png)' : ''}; zero errors required. Iterate until your honest re-assessment is >= ${THRESH}. Do not commit.`, { label: `fix:${f.module}:r${round}`, phase: 'Revise', schema: FIX, effort: EFFORT[f.module] })))

  phase('Integrate')
  const contractNotes = fixes.filter(Boolean).flatMap((x) => x.notAddressed.filter((n) => n.startsWith('CONTRACT:')).map((n) => `${x.module}: ${n}`))
  const e = await agent(`You are the INTEGRATOR for "A-MAZE" (${ROOT}). Modules just revised in parallel: ${failing.map((f) => f.module).join(', ')}.${contractNotes.length ? ` Contract change requests: ${contractNotes.join(' | ')} — apply them in ARCHITECTURE.md and all consumers if sound.` : ''} Run ${evidencePrompt.split('Run, capturing output: ')[1].split('. Then')[0]}. Fix integration errors (contract drift, broken imports, seam mismatches) surgically in src/main.js, tools/, or the seam inside a module (comment why). Re-run until everything passes with zero console errors. READ the verify screenshots to make sure nothing regressed visually. Then commit only source + docs (never git add -A): \`git add src tools index.html styles.css ARCHITECTURE.md CLAUDE.md && git commit -m "Gauntlet round ${round}: ${failing.map((f) => f.module).join(', ')} revisions" -m "Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"\` (retry once on index.lock). Return the same compact evidence summary format (commands pass/fail, errors, validate/stress numbers, verify essentials + screenshot paths).`, { label: `integrator:r${round}`, phase: 'Integrate', schema: EVIDENCE, effort: 'high' })
  if (e) evidence = e
}

phase('Stress Gate')
const stress = await agent(`You are the FINAL STRESS GATE for "A-MAZE" (${ROOT}). Do not modify src/ unless you find a real defect (then fix minimally, re-run, and report it). 1) Run \`node tools/stress.mjs\` and additionally a scratchpad script in logs/ that pushes generateMaze+validateMaze+buildLevel to the extreme limits the API accepts (e.g. 4096x1, 1x4096, 2048x2048, 3000x3000 if allowed, braid 1.0 at 1000x1000) and at/over the limit (expect clean RangeError, never a hang, stack overflow or OOM crash), recording ms & heap; verify no recursion via grep. 2) Headless Chrome (puppeteer-core, Chrome at C:/Program Files/Google/Chrome/Application/chrome.exe) at /?headless=1: force-build a 40x40 level (max gameplay size) and a 200x200 level through the maze client (worker path) while measuring that the render loop keeps producing frames during generation (rAF gap max < 50ms), then a 60-second autopilot soak on the largest level measuring fps, frame-time p99, dropped frames, and JS heap before/after forced GC (CDP HeapProfiler.collectGarbage) — growth must be < 5MB; also count event listeners via CDP DOMDebugger.getEventListeners on window/document before and after 5 newGame→gameOver→toTitle cycles (must not grow). 3) Run with CPU throttled 4x and report fps. PASS criteria: zero infinite loops/stack overflows/crashes, zero console errors, fps >= 55 unthrottled, frame p99 < 20ms, heap growth < 5MB, listeners stable, worker generation never blocks frames. Write logs/stress-gate.json. Return summary + pass flag.`, { label: 'stress-gate', phase: 'Stress Gate', schema: EVIDENCE, effort: 'high' })

phase('Status')
const final = Object.fromEntries(Object.entries(scores).map(([k, v]) => [k, { score: v.score, round: v.round, pass: v.passed, errors: v.errors, verdict: v.verdict, issues: v.issues.map((i) => `[${i.severity}] ${i.file}: ${i.issue} → ${i.fix}`) }]))
await agent(`Root ${ROOT}. Update docs/STATUS.json (read first; keep shape). Set waves.gauntlet = {status: all modules pass ? "done" : "failing", rounds}, waves.stress = {status: stress pass ? "done" : "failing", summary}. Replace "modules" entries for the scored modules with the data below. Set metrics from logs/gauntlet.json / logs/fix-*.json (latest) and logs/stress-gate.json (fps, renderMs, heapGrowth, errors, largest grid). Put every failing module's high/blocker issues and a failed stress gate into "blocking" (remove blockers now proven fixed). Increment iteration, updated = current UTC ISO from node, append {iteration, updated, wave:"gauntlet", scores map, stressPass} to history. Then \`git add docs/STATUS.json && git commit -m "STATUS: gauntlet iteration" -m "Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"\`. Return one line.\n\nScores:\n${JSON.stringify(final, null, 1)}\nHistory: ${JSON.stringify(history)}\nStress gate: ${JSON.stringify(stress)}`, { label: 'status-writer', phase: 'Status', effort: 'low' })

return { scores: final, history, stress, allPass: Object.values(scores).every((s) => s.passed) && !!stress?.allPass }
