// @ts-check
/**
 * @file Maze generation: iterative randomized depth-first search ("recursive backtracker"),
 * optional cross-section shortcuts, optional braiding, and farthest-cell exit selection
 * (ARCHITECTURE.md §4.4).
 *
 * ## Why the backtracker
 * It produces long, winding, low-branching corridors — exactly the "lost in a dungeon" feel the
 * game wants — where Kruskal/Prim produce bushier, more uniform mazes. It is also O(n) in both
 * time and memory with a trivially explicit stack.
 *
 * ## Mathematical guarantee: the carve pass always yields a spanning tree
 * Let the *cell graph* G have one node per logical cell and an edge between orthogonally adjacent
 * cells. The carve loop maintains three invariants:
 *
 *   I1. A cell is pushed on the stack exactly when it is first marked visited, and it is never
 *       marked visited twice (the only write to `visited` is guarded by `visited[n] === 0`).
 *       Therefore **every cell is visited at most once** and the stack holds distinct cells, so
 *       `stack` needs at most `cols*rows` slots — no recursion, no stack overflow at any size.
 *   I2. Every carve opens the wall between the current cell (already visited) and a neighbour that
 *       was *not* visited. So each carved edge joins a new node to the already-built structure:
 *       after k carves the visited set is connected and contains k+1 cells, and **no carve can
 *       ever close a cycle** (a cycle would need both endpoints already visited).
 *   I3. The loop only pops a cell when it has no unvisited neighbours, and only terminates when
 *       the stack is empty — i.e. when no visited cell has an unvisited neighbour. Since the grid
 *       graph is connected, an unvisited cell would have to be adjacent to some visited cell
 *       (walk any grid path from the start cell to it and take the first crossing), contradiction.
 *       Therefore **every cell is visited** on termination.
 *
 * From I1+I3 the visited set is all n = cols*rows cells; from I2 the carved edges number exactly
 * n−1 and form a connected acyclic subgraph. A connected acyclic spanning subgraph *is* a spanning
 * tree, hence: every cell reachable from every other cell, by exactly one simple path, with
 * `loops = edges − (nodes − 1) = 0`. That is what `validateMaze` asserts and what
 * `tools/validate-mazes.mjs` checks for 100 % of the braid-0 matrix.
 *
 * ## Why braiding cannot break any of that
 * Braiding **only ever turns a WALL tile into a FLOOR tile**; it never fills a corridor back in.
 * Adding an edge to a connected graph leaves it connected, so solvability and full connectivity
 * survive by construction — braiding can only *increase* `loops` (each removed wall adds one edge
 * to a graph whose node count is unchanged) and *decrease* the number of dead ends. No
 * re-validation of connectivity is needed after braiding; it is a theorem, not a hope. The
 * shortcut pass (`connectSections`) is the same kind of operation — WALL → FLOOR between two
 * cells — so the same argument covers it.
 *
 * ## The route guard, and why it has a budget
 * Both wall-opening passes can be asked to keep the start→exit route from collapsing (see
 * {@link RouteGuard}). The guard is exact — it maintains BFS distances from the start and from a
 * reference exit and repairs them after every opened wall — up to a repair budget of
 * `SHORTCUT_REPAIR_BUDGET` lowered cells *per maze cell*. Past that it keeps the identical promise
 * with an O(1) Lipschitz test instead. That is what makes the whole generator O(cells): without it
 * a 2000×2000 build at the campaign's shortcut density took 91 s (22.8 µs per cell against 2.7 at
 * the 128×128 gameplay cap), because one wall near the root of a big tree lowers the distance of a
 * large share of the maze. The budget is ~2.8× the worst repair cost measured anywhere on the
 * shipped level curve, so every level the game actually builds is generated by the exact guard,
 * bit for bit as before; `tools/stress.mjs` holds the per-cell cost at the sizes past it.
 *
 * ## Units & conventions
 * Tile coordinates, row-major indexing, thick walls and direction numbering are all defined in
 * `constants.js`. Cell (cx,cy) ⇒ tile (2cx+1, 2cy+1); the gap tile toward direction d is
 * (2cx+1+dx[d], 2cy+1+dy[d]).
 */

import { createRng } from '../core/rng.js';
import { clamp } from '../core/math.js';
import { TILE, DIR_COUNT, DIR_DX, DIR_DY, MAX_CELLS_PER_SIDE } from './constants.js';

/** @typedef {import('../core/types.js').Maze} Maze */

/**
 * Parameters for {@link generateMaze}.
 * @typedef {Object} GenerateParams
 * @property {number} cols   logical cell columns, 1..4096 (`MAX_CELLS_PER_SIDE`)
 * @property {number} rows   logical cell rows, 1..4096
 * @property {number} seed   any finite number; NaN/±Infinity are treated as 0
 * @property {number} [braid=0] fraction of dead ends to open up, clamped to 0..1
 * @property {number} [shortcuts=0] walls to knock through between cells that are far apart by
 *   path (see {@link connectSections}); floored, clamped to ≥ 0
 * @property {number} [shortcutDetour=SHORTCUT_DETOUR] minimum path distance, in cells, between the
 *   two cells a shortcut joins; floored, clamped to ≥ 2
 * @property {number} [shortcutRouteKeep=SHORTCUT_ROUTE_KEEP] fraction (0..1) of the start→exit
 *   route length that shortcuts must leave intact
 * @property {number} [braidRouteKeep=BRAID_ROUTE_KEEP] fraction (0..1) of the *post-shortcut*
 *   start→exit route that braiding must leave intact; 0 (the default) lets braiding shorten the
 *   route as far as it likes, which is what the shipped difficulty curve asks for
 */

/**
 * Default minimum detour a shortcut must save, in cells. Two neighbours this far apart by path sit
 * in genuinely different sections of the maze, so the opening turns a long backtrack into a loop;
 * a smaller value would mostly join sibling corridors and change nothing the player can feel.
 */
export const SHORTCUT_DETOUR = 12;

/**
 * Default fraction of the carved start→exit route that shortcuts must preserve. Shortcuts exist to
 * spare the player long backtracks, not to trivialise the level: unguarded, four shortcuts halve
 * a 16×16 route (measured 314 → 150 tiles).
 */
export const SHORTCUT_ROUTE_KEEP = 0.85;

/**
 * Default fraction of the post-shortcut route that **braiding** must preserve. Zero, because
 * braiding *is* the difficulty curve's route brake rather than a threat to it: `LEVEL.BRAID_MAX`
 * in `src/state/balance.js` exists precisely because a perfect 128×128 maze carries a 10 600-tile
 * (~48-minute) route, and the ramp that cuts it to ~700 tiles is what keeps the curve monotone.
 *
 * The knob exists so that a curve which wants longer deep levels can ask for a floor instead of
 * the generator guessing. Measured at the 128×128 cap (5 seeds, shipped `levelParams`), final
 * route in tiles: 715 at 0 (the shipped default), 905 at 0.10, 1 016 at 0.12, 1 173 at 0.15 and
 * 1 956 at 0.25; dead ends rise slightly with it (255 → 278), because a dead end whose every
 * direction is refused stays a dead end. Whether a deep level *should* be a 9-minute walk or a
 * 15-minute one is a balance decision, and this file does not make it.
 */
export const BRAID_ROUTE_KEEP = 0;

/**
 * Validate one grid dimension. Non-integers are floored (a caller computing `cols` from a curve
 * should not have to round), but genuinely nonsensical values throw rather than being silently
 * clamped, because a clamped NaN would hide the bug that produced it.
 * @param {unknown} value
 * @param {'cols'|'rows'} name
 * @returns {number} integer in 1..MAX_CELLS_PER_SIDE
 * @throws {RangeError} when `value` is not finite, below 1, or above `MAX_CELLS_PER_SIDE`
 */
function requireSide(value, name) {
  const n = Number(value);
  if (!Number.isFinite(n)) {
    throw new RangeError(`generateMaze: ${name} must be a finite number, got ${String(value)}`);
  }
  const i = Math.floor(n);
  if (i < 1 || i > MAX_CELLS_PER_SIDE) {
    throw new RangeError(`generateMaze: ${name} must be 1..${MAX_CELLS_PER_SIDE}, got ${n}`);
  }
  return i;
}

/**
 * Normalise the seed. `createRng` already maps NaN/±Infinity to stream 0, but `Maze.seed` is part
 * of the save format and must be a plain finite number, so it is normalised here too.
 * @param {unknown} value
 * @returns {number} finite number (0 when the input is not finite)
 */
function normalizeSeed(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Normalise a non-negative integer parameter: floor, clamp to `min`, and treat anything
 * non-numeric as `fallback`.
 * @param {unknown} value
 * @param {number} min
 * @param {number} fallback
 * @returns {number}
 */
function normalizeCount(value, min, fallback) {
  if (value === undefined || value === null) return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? Math.max(min, Math.floor(n)) : fallback;
}

/**
 * Normalise a 0..1 fraction: clamp into range, fall back to `fallback` when the value is absent or
 * not a finite number.
 * @param {unknown} value
 * @param {number} fallback
 * @returns {number} 0..1
 */
function normalizeFraction(value, fallback) {
  const n = Number(value ?? NaN);
  return Number.isFinite(n) ? clamp(n, 0, 1) : fallback;
}

/**
 * Generate a thick-wall maze.
 *
 * Deterministic: the same parameters always produce bit-identical `tiles`, in Node and in every
 * browser. The carve, shortcut and braid passes draw from three *forked* streams (`maze.carve`,
 * `maze.connect`, `maze.braid`), so changing one knob never reshuffles the base maze.
 *
 * Cost: **O(cols·rows)** at every size. The carve and the braid are linear by inspection; the
 * shortcut pass costs one bounded BFS per candidate wall (O(detour²) cells) plus its route guard's
 * repairs, which are capped at `SHORTCUT_REPAIR_BUDGET` lowered cells *per maze cell* — past that
 * the guard keeps its promise with an O(1) test instead (see {@link RouteGuard}). Measured with
 * the campaign's own shortcut density (cells/4, detour 4, keep 0.7): 1.6 µs per cell at 256²,
 * 4.5 at 1000², 7.5 at 2000² braid 0.6 — 30 s for a 4 M-cell maze, against 91 s before the cap.
 * Memory is the tile buffer ((2c+1)(2r+1) bytes) plus ~9 bytes per cell of scratch (~25 with the
 * route guard's two distance fields), all released on return.
 *
 * @param {GenerateParams} params
 * @returns {Maze} a fully carved maze whose `start` is cell (0,0) and whose `exit` is the cell at
 *   maximum BFS distance from the start *in the final (post-braid) maze*
 * @throws {RangeError} when `params` is not an object, or `cols`/`rows` are not 1..4096
 */
export function generateMaze(params) {
  if (params === null || typeof params !== 'object') {
    throw new RangeError(`generateMaze: params must be an object, got ${String(params)}`);
  }
  const cols = requireSide(params.cols, 'cols');
  const rows = requireSide(params.rows, 'rows');
  const seed = normalizeSeed(params.seed);
  const braid = normalizeFraction(params.braid, 0); // no braiding is the safe default
  const shortcuts = normalizeCount(params.shortcuts, 0, 0);
  const shortcutDetour = normalizeCount(params.shortcutDetour, 2, SHORTCUT_DETOUR);
  const routeKeep = normalizeFraction(params.shortcutRouteKeep, SHORTCUT_ROUTE_KEEP);
  const braidKeep = normalizeFraction(params.braidRouteKeep, BRAID_ROUTE_KEEP);

  const width = cols * 2 + 1;
  const height = rows * 2 + 1;

  // Start from solid rock and carve. (Uint8Array is zero-filled = FLOOR, so the fill is required.)
  const tiles = new Uint8Array(width * height).fill(TILE.WALL);

  const rng = createRng(seed);
  carve(tiles, width, cols, rows, rng.fork('maze.carve'));
  if (shortcuts > 0) {
    connectSections(tiles, width, cols, rows, shortcuts, shortcutDetour, routeKeep, rng.fork('maze.connect'));
  }
  if (braid > 0) braidDeadEnds(tiles, width, cols, rows, braid, braidKeep, rng.fork('maze.braid'));

  const exitCell = farthestCell(tiles, width, cols, rows, 0);
  const ex = exitCell % cols;
  const ey = (exitCell - ex) / cols;

  return {
    width,
    height,
    cols,
    rows,
    tiles,
    start: { x: 1, y: 1 },
    exit: { x: ex * 2 + 1, y: ey * 2 + 1 },
    seed,
  };
}

/**
 * Carve a spanning tree with an iterative randomized DFS (see the file header for the proof).
 * Allocates exactly three typed arrays (visited, stack, 4-slot candidate scratch) and nothing at
 * all inside the loop.
 * @param {Uint8Array} tiles   width*height tile buffer, pre-filled with WALL (mutated)
 * @param {number} width       tile columns
 * @param {number} cols        cell columns
 * @param {number} rows        cell rows
 * @param {import('../core/rng.js').Rng} rng
 * @returns {void}
 */
function carve(tiles, width, cols, rows, rng) {
  const nCells = cols * rows;
  const visited = new Uint8Array(nCells);
  const stack = new Int32Array(nCells); // I1: each cell is pushed at most once ⇒ this always fits
  const candidates = new Int32Array(DIR_COUNT);

  let top = 0;
  stack[0] = 0;
  visited[0] = 1;
  tiles[1 * width + 1] = TILE.FLOOR; // cell (0,0)

  while (top >= 0) {
    const cell = stack[top];
    const cx = cell % cols;
    const cy = (cell - cx) / cols;

    // Collect the unvisited neighbours. Four iterations, no allocation, no sorting.
    let k = 0;
    for (let d = 0; d < DIR_COUNT; d++) {
      const nx = cx + DIR_DX[d];
      const ny = cy + DIR_DY[d];
      if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
      if (visited[ny * cols + nx] !== 0) continue;
      candidates[k++] = d;
    }

    if (k === 0) {
      // Dead end for the walker: backtrack. (I3: we only stop when nothing is reachable.)
      top--;
      continue;
    }

    // `rng.int(1)` consumes no draw, so a forced choice keeps the stream aligned with a maze that
    // happened to have several options — determinism does not depend on branch counts.
    const d = candidates[rng.int(k)];
    const tx = cx * 2 + 1;
    const ty = cy * 2 + 1;
    tiles[(ty + DIR_DY[d]) * width + (tx + DIR_DX[d])] = TILE.FLOOR; // the wall between the cells
    const nx = cx + DIR_DX[d];
    const ny = cy + DIR_DY[d];
    tiles[(ny * 2 + 1) * width + (nx * 2 + 1)] = TILE.FLOOR; // the neighbour cell itself
    const nCell = ny * cols + nx;
    visited[nCell] = 1;
    stack[++top] = nCell;
  }
}

/**
 * Count a cell's open edges (corridors leaving it) and record the walled, in-bounds directions.
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} cx
 * @param {number} cy
 * @param {Int32Array} walledOut  4-slot scratch, filled with the closed in-bounds directions
 * @returns {number} packed result: `openCount | (walledCount << 8)` — packing avoids allocating a
 *   pair in a loop that runs once per dead end
 */
function probeCell(tiles, width, cols, rows, cx, cy, walledOut) {
  const tx = cx * 2 + 1;
  const ty = cy * 2 + 1;
  let open = 0;
  let walled = 0;
  for (let d = 0; d < DIR_COUNT; d++) {
    const nx = cx + DIR_DX[d];
    const ny = cy + DIR_DY[d];
    if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
    if (tiles[(ty + DIR_DY[d]) * width + (tx + DIR_DX[d])] === TILE.FLOOR) open++;
    else walledOut[walled++] = d;
  }
  return open | (walled << 8);
}

/**
 * Route guard shared by the shortcut and braid passes: the machinery that keeps a pass from
 * knocking the start→exit route below a fraction of what it was when the guard was built.
 *
 * `ds`/`de` are BFS distances (in cells) from the start and from the reference exit — the farthest
 * cell at that moment. A shortest path crosses a newly opened edge (a,b) at most once, so the route
 * through it is `min(ds[a]+1+de[b], ds[b]+1+de[a])`, and rejecting anything below `minRoute` keeps
 * the route at or above it. The final exit is still chosen afterwards as the farthest cell, which
 * is at least as far as the reference exit, so the guarantee survives to the shipped maze.
 *
 * **Why there is a budget.** Repairing both fields after an opened wall costs one BFS over the
 * cells that actually got closer, and near the root of a big tree that is a large share of the
 * maze: the repairs, not the candidate tests, are what made this pass superlinear (measured 21 µs
 * per cell at 1000², 91 s for a 2000² build at campaign shortcut density). Once `work` — cells
 * lowered, summed over every repair — passes `budget = SHORTCUT_REPAIR_BUDGET · cells`, the guard
 * stops repairing and switches to a rule that needs no repair at all (`exact` becomes false):
 *
 *   `min(ds, minRoute)` is 1-Lipschitz over the open corridors, 0 at the start and `minRoute` at
 *   the reference exit, so *any* start→exit walk costs at least `minRoute` steps. Opening a wall
 *   whose two cells are within 1 of each other in `ds` keeps it 1-Lipschitz — and leaves `ds`
 *   itself exact, since neither endpoint can now be reached any faster through the other. So the
 *   inexact phase enforces the same guarantee with an O(1) test, at the price of turning down
 *   walls the exact test would have taken.
 *
 * That is what makes generation O(cells) at every size: the budget is per cell, and the tail is
 * O(1) per candidate. The budget is ~2.8× the worst repair cost measured anywhere on the shipped
 * level curve (46 lowered cells per maze cell at the 128×128 cap), so no level the game builds
 * ever reaches the tail — measured, it first binds at ~700×700 cells, a size only
 * `tools/stress.mjs` and the generator's own scaling test ever visit.
 *
 * @typedef {Object} RouteGuard
 * @property {Int32Array} ds        distances from the start cell, always exact
 * @property {Int32Array} de        distances from the reference exit; stale once `exact` is false
 * @property {Int32Array} queue     cols*rows slots of BFS scratch
 * @property {Int32Array} queueTile cols*rows slots of scratch, tile indices beside `queue`
 * @property {number} exitCell      the reference exit
 * @property {number} minRoute      cells the start→exit route may never fall below
 * @property {number} work          cells lowered by repairs so far
 * @property {number} budget        `work` at which the guard stops repairing
 * @property {boolean} exact        false once the guard runs on the Lipschitz rule alone
 */

/**
 * Cells lowered per maze cell that a route guard will spend on repairing its distance fields
 * before it falls back to the repair-free rule (see {@link RouteGuard}).
 */
const SHORTCUT_REPAIR_BUDGET = 128;

/**
 * Build a route guard for the maze as it stands.
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} keep   0..1 fraction of the current route to preserve
 * @param {Int32Array} queue cols*rows slots of scratch, borrowed for the two BFS passes
 * @returns {RouteGuard}
 */
function createRouteGuard(tiles, width, cols, rows, keep, queue) {
  const nCells = cols * rows;
  const ds = new Int32Array(nCells);
  const de = new Int32Array(nCells);
  const exitCell = distancesFrom(tiles, width, cols, rows, 0, ds, queue);
  distancesFrom(tiles, width, cols, rows, exitCell, de, queue);
  return {
    ds,
    de,
    queue,
    queueTile: new Int32Array(nCells),
    exitCell,
    minRoute: Math.ceil(ds[exitCell] * keep),
    work: 0,
    budget: SHORTCUT_REPAIR_BUDGET * nCells,
    exact: true,
  };
}

/**
 * May the wall between cells `a` and `b` be opened without cutting the route below `minRoute`?
 * @param {RouteGuard} guard
 * @param {number} a
 * @param {number} b
 * @returns {boolean}
 */
function guardAllows(guard, a, b) {
  const { ds } = guard;
  if (!guard.exact) {
    const step = ds[a] - ds[b];
    return step <= 1 && step >= -1;
  }
  return ds[a] + 1 + guard.de[b] >= guard.minRoute && ds[b] + 1 + guard.de[a] >= guard.minRoute;
}

/**
 * Tell the guard that the wall between `a` and `b` is now open, repairing its fields while the
 * repair budget lasts.
 * @param {RouteGuard} guard
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} a
 * @param {number} b
 * @returns {void}
 */
function guardOpened(guard, tiles, width, cols, a, b) {
  if (!guard.exact) return; // the Lipschitz rule leaves both `ds` and the guarantee intact
  guard.work += relaxDistances(tiles, width, cols, guard.ds, a, b, guard.queue, guard.queueTile);
  guard.work += relaxDistances(tiles, width, cols, guard.de, a, b, guard.queue, guard.queueTile);
  if (guard.work >= guard.budget) guard.exact = false;
}

/**
 * Shortcut pass: knock through up to `count` interior walls whose two cells are at least `detour`
 * cells apart by path, joining separate sections of the maze.
 *
 * Braiding only opens dead ends, and its dead-end-to-dead-end preference mostly joins neighbouring
 * twigs of the same branch — the player still walks out of a long cul-de-sac the way they came in.
 * This pass instead picks walls at random and keeps one only when a **bounded BFS** from one side
 * cannot reach the other in fewer than `detour` steps, i.e. the wall separates two places the
 * current maze (earlier shortcuts included) keeps far apart. That gives dead-end sections an
 * occasional back door and lets corridors that "should" meet actually meet — so the player's
 * mental map stops being a tree, and getting lost becomes possible.
 *
 * Because each test runs on the live tiles, a new shortcut is never placed where an earlier one
 * already brought the two sides close: shortcuts spread out without an explicit spacing rule.
 *
 * The start→exit route is protected by a {@link RouteGuard} at `routeKeep` of the carved route;
 * `routeKeep ≤ 0` skips the distance fields entirely rather than maintaining fields nothing reads.
 *
 * Cost: one shuffle of ≈ 2·cols·rows candidate walls; per candidate a BFS capped at `detour` steps
 * (O(detour²) cells, a few dozen at the shipped detours); per accepted wall a guard repair, capped
 * in total at `SHORTCUT_REPAIR_BUDGET · cells` lowered cells. Linear in the maze at every size.
 * Stops at `count` successes or when the candidates run out — never more than `count`.
 *
 * @param {Uint8Array} tiles   mutated in place
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} count       maximum walls to open
 * @param {number} detour      minimum path distance (cells) between the two joined cells, ≥ 2
 * @param {number} routeKeep   0..1 fraction of the start→exit route to preserve
 * @param {import('../core/rng.js').Rng} rng
 * @returns {number} number of walls actually removed
 */
function connectSections(tiles, width, cols, rows, count, detour, routeKeep, rng) {
  const nCells = cols * rows;
  const nWalls = (cols - 1) * rows + cols * (rows - 1);
  if (nWalls === 0 || count <= 0) return 0;

  // Candidate walls, encoded `cell * 2 + d` (d = DIR_E 0 or DIR_S 1). After the carve n−1 of them
  // are open tree edges; those are skipped when reached rather than filtered up front.
  const walls = new Int32Array(nWalls);
  let w = 0;
  for (let cy = 0; cy < rows; cy++) {
    for (let cx = 0; cx < cols; cx++) {
      const cell = cy * cols + cx;
      if (cx + 1 < cols) walls[w++] = cell * 2;
      if (cy + 1 < rows) walls[w++] = cell * 2 + 1;
    }
  }
  rng.shuffle(walls);

  // Bounded-BFS scratch; `stamp` avoids clearing `mark` between searches.
  const queue = new Int32Array(nCells);
  const scratch = { mark: new Int32Array(nCells), dist: new Int32Array(nCells), queue, stamp: 0 };
  const guard = routeKeep > 0 ? createRouteGuard(tiles, width, cols, rows, routeKeep, queue) : null;

  let removed = 0;
  for (let i = 0; i < nWalls && removed < count; i++) {
    const code = walls[i];
    const cell = code >> 1;
    const d = code & 1;
    const cx = cell % cols;
    const cy = (cell - cx) / cols;
    const gap = (cy * 2 + 1 + DIR_DY[d]) * width + (cx * 2 + 1 + DIR_DX[d]);
    if (tiles[gap] === TILE.FLOOR) continue;
    const target = (cy + DIR_DY[d]) * cols + (cx + DIR_DX[d]);
    if (guard !== null && !guardAllows(guard, cell, target)) continue;
    if (!farApart(tiles, width, cols, rows, cell, target, detour, scratch)) continue;

    tiles[gap] = TILE.FLOOR;
    removed++;
    if (guard !== null) guardOpened(guard, tiles, width, cols, cell, target);
  }
  return removed;
}

/**
 * Bounded BFS on the live tiles: is `target` out of reach of `cell` in fewer than `detour` steps?
 *
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} cell     one side of the wall
 * @param {number} target   the other side
 * @param {number} detour   minimum path distance (cells) the two sides must be apart
 * @param {{mark:Int32Array, dist:Int32Array, queue:Int32Array, stamp:number}} scratch  reused
 *   across calls; `stamp` is advanced so `mark` never needs clearing
 * @returns {boolean} true when the two cells are at least `detour` steps apart
 */
function farApart(tiles, width, cols, rows, cell, target, detour, scratch) {
  const { mark, dist, queue } = scratch;
  const stamp = ++scratch.stamp;
  let head = 0;
  let tail = 0;
  mark[cell] = stamp;
  dist[cell] = 0;
  queue[tail++] = cell;
  while (head < tail) {
    const c = queue[head++];
    const nd = dist[c] + 1;
    if (nd >= detour) break; // BFS order: every cell still queued is at least this far
    const qx = c % cols;
    const qy = (c - qx) / cols;
    const tx = qx * 2 + 1;
    const ty = qy * 2 + 1;
    for (let k = 0; k < DIR_COUNT; k++) {
      const nx = qx + DIR_DX[k];
      const ny = qy + DIR_DY[k];
      if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
      if (tiles[(ty + DIR_DY[k]) * width + (tx + DIR_DX[k])] !== TILE.FLOOR) continue;
      const n = ny * cols + nx;
      if (mark[n] === stamp) continue;
      if (n === target) return false;
      mark[n] = stamp;
      dist[n] = nd;
      queue[tail++] = n;
    }
  }
  return true;
}

/**
 * Repair a BFS distance field after the edge (a,b) was opened. Opening an edge can only shorten
 * distances, and only through that edge, so it is enough to seed the farther endpoint with its
 * improved distance and propagate improvements outward — the work is proportional to the cells
 * that actually got closer, not to the maze.
 *
 * This is the hot loop of the whole generator (the route guard runs it after every accepted wall),
 * so it walks cell *and* tile indices side by side instead of recovering `cx`/`cy` with a modulo
 * per cell: a step east is `cell + 1` / `tile + 2`, a step south `cell + cols` / `tile + 2·width`.
 * The bounds checks go with them — the maze's outer ring is WALL by construction, and the gap tile
 * a step off the grid *is* that ring, so the floor test rejects every wrap-around on its own.
 *
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {Int32Array} dist  a complete distance field (no -1 entries: the maze is connected); mutated
 * @param {number} a
 * @param {number} b
 * @param {Int32Array} queue cols*rows slots of scratch
 * @param {Int32Array} queueTile cols*rows slots of scratch, the tile index of each queued cell
 * @returns {number} cells whose distance was lowered (the repair's cost, for the work budget)
 */
function relaxDistances(tiles, width, cols, dist, a, b, queue, queueTile) {
  let head = 0;
  let tail = 0;
  if (dist[a] + 1 < dist[b]) {
    dist[b] = dist[a] + 1;
    queue[tail] = b;
    queueTile[tail++] = cellTile(b, width, cols);
  } else if (dist[b] + 1 < dist[a]) {
    dist[a] = dist[b] + 1;
    queue[tail] = a;
    queueTile[tail++] = cellTile(a, width, cols);
  }
  const rowStride = width * 2;
  // Every enqueue strictly lowers a distance and the queue is FIFO over a BFS frontier, so a cell
  // is enqueued at most once per call and `tail` never exceeds the scratch capacity.
  while (head < tail) {
    const c = queue[head];
    const t = queueTile[head++];
    const nd = dist[c] + 1;
    if (tiles[t + 1] === TILE.FLOOR && dist[c + 1] > nd) {
      dist[c + 1] = nd;
      queue[tail] = c + 1;
      queueTile[tail++] = t + 2;
    }
    if (tiles[t - 1] === TILE.FLOOR && dist[c - 1] > nd) {
      dist[c - 1] = nd;
      queue[tail] = c - 1;
      queueTile[tail++] = t - 2;
    }
    if (tiles[t + width] === TILE.FLOOR && dist[c + cols] > nd) {
      dist[c + cols] = nd;
      queue[tail] = c + cols;
      queueTile[tail++] = t + rowStride;
    }
    if (tiles[t - width] === TILE.FLOOR && dist[c - cols] > nd) {
      dist[c - cols] = nd;
      queue[tail] = c - cols;
      queueTile[tail++] = t - rowStride;
    }
  }
  return tail;
}

/**
 * Tile index of a cell's own tile.
 * @param {number} cell
 * @param {number} width
 * @param {number} cols
 * @returns {number}
 */
function cellTile(cell, width, cols) {
  const cx = cell % cols;
  return ((cell - cx) / cols) * 2 * width + width + cx * 2 + 1;
}

/**
 * Braid pass: open a wall at `braid` (0..1) of the maze's dead ends, turning the perfect maze into
 * one with loops. Only removes walls, so connectivity is preserved by construction.
 *
 * Choice policy (classic Jamis-Buck braiding): among a dead end's walled neighbours, prefer one
 * that is *itself* a dead end — that removes two dead ends with one wall and produces more
 * natural-looking loops than a purely random pick. Ties are broken by the braid stream.
 *
 * A dead end whose only walled neighbours are out of bounds (e.g. the tip of a 1×N corridor)
 * cannot be braided and is skipped; that is why the achieved count can be lower than requested for
 * degenerate shapes. It is never higher.
 *
 * **Route guard (`routeKeep > 0`).** Braiding is by far the biggest thing that happens to the
 * route: measured on the shipped curve at the 128×128 cap it takes a 7 433-tile post-shortcut route
 * down to ~715 tiles, which is *why* `BRAID_MAX` exists (a perfect maze of that size is a 48-minute
 * walk). Unguarded, though, it also undoes the shortcut pass's route guarantee, so `routeKeep`
 * gives the caller a floor: the same {@link RouteGuard} machinery, built on the maze as the braid
 * pass finds it, rejects any wall that would take the route below `routeKeep` of it and tries the
 * dead end's other walled directions instead. A dead end with no allowed direction is left alone,
 * so a floor costs dead ends removed, not solvability. `routeKeep = 0` (the default, and what the
 * shipped curve asks for) keeps the historical behaviour: braid cuts the route as much as it likes.
 *
 * @param {Uint8Array} tiles  mutated in place
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} braid      0..1 fraction of dead ends to open
 * @param {number} routeKeep  0..1 fraction of the pre-braid start→exit route to preserve; 0 = no guard
 * @param {import('../core/rng.js').Rng} rng
 * @returns {number} number of walls actually removed
 */
function braidDeadEnds(tiles, width, cols, rows, braid, routeKeep, rng) {
  const nCells = cols * rows;
  if (nCells < 2) return 0; // a single cell has no wall that could be removed without unsealing

  const walled = new Int32Array(DIR_COUNT); // closed directions of the dead end being processed
  const preferred = new Int32Array(DIR_COUNT); // subset of `walled` leading to another dead end
  const allowed = new Int32Array(DIR_COUNT); // subset of `walled` the route guard permits
  const probeScratch = new Int32Array(DIR_COUNT); // throwaway output when probing a neighbour

  // Pass 1: count dead ends so the index list can be sized exactly (no growing array).
  let deadCount = 0;
  for (let cy = 0; cy < rows; cy++) {
    for (let cx = 0; cx < cols; cx++) {
      if ((probeCell(tiles, width, cols, rows, cx, cy, walled) & 0xff) === 1) deadCount++;
    }
  }
  if (deadCount === 0) return 0;

  // Pass 2: collect them, shuffle, and process the first `target`.
  const deadEnds = new Int32Array(deadCount);
  let w = 0;
  for (let cy = 0; cy < rows; cy++) {
    for (let cx = 0; cx < cols; cx++) {
      if ((probeCell(tiles, width, cols, rows, cx, cy, walled) & 0xff) === 1) {
        deadEnds[w++] = cy * cols + cx;
      }
    }
  }
  rng.shuffle(deadEnds);

  const guard =
    routeKeep > 0 ? createRouteGuard(tiles, width, cols, rows, routeKeep, new Int32Array(nCells)) : null;
  const target = Math.round(deadCount * braid);
  let removed = 0;
  for (let i = 0; i < target; i++) {
    const cell = deadEnds[i];
    const cx = cell % cols;
    const cy = (cell - cx) / cols;
    const probe = probeCell(tiles, width, cols, rows, cx, cy, walled);
    // An earlier braid may already have opened this cell up; skip it rather than over-braiding.
    if ((probe & 0xff) !== 1) continue;
    let walledCount = probe >> 8;
    if (walledCount === 0) continue; // corridor tip against the outer border

    // Drop the directions the route guard forbids; a dead end with none left stays a dead end.
    if (guard !== null) {
      let ok = 0;
      for (let j = 0; j < walledCount; j++) {
        const d = walled[j];
        const n = (cy + DIR_DY[d]) * cols + (cx + DIR_DX[d]);
        if (guardAllows(guard, cell, n)) allowed[ok++] = d;
      }
      if (ok === 0) continue;
      for (let j = 0; j < ok; j++) walled[j] = allowed[j];
      walledCount = ok;
    }

    // Prefer a walled neighbour that is itself a dead end.
    let deadNeighbours = 0;
    for (let j = 0; j < walledCount; j++) {
      const d = walled[j];
      const nx = cx + DIR_DX[d];
      const ny = cy + DIR_DY[d];
      if ((probeCell(tiles, width, cols, rows, nx, ny, probeScratch) & 0xff) === 1) {
        preferred[deadNeighbours++] = d;
      }
    }
    const chosen = deadNeighbours > 0 ? preferred[rng.int(deadNeighbours)] : walled[rng.int(walledCount)];

    const tx = cx * 2 + 1;
    const ty = cy * 2 + 1;
    tiles[(ty + DIR_DY[chosen]) * width + (tx + DIR_DX[chosen])] = TILE.FLOOR;
    removed++;
    if (guard !== null) {
      guardOpened(guard, tiles, width, cols, cell, (cy + DIR_DY[chosen]) * cols + (cx + DIR_DX[chosen]));
    }
  }
  return removed;
}

/**
 * Breadth-first search over the cell graph from `fromCell`, returning the index of the cell at
 * maximum distance. BFS dequeues in non-decreasing distance order, so "first cell discovered at
 * the maximum distance" is a deterministic tie-break given the fixed E,S,W,N neighbour order.
 *
 * Runs on the *final* tiles, so with braiding the exit is farthest in the braided maze (shortcuts
 * included) rather than in the tree that preceded it.
 *
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} fromCell  source cell index (`cy*cols + cx`)
 * @returns {number} cell index of a farthest cell (equals `fromCell` for a 1×1 maze)
 */
function farthestCell(tiles, width, cols, rows, fromCell) {
  const nCells = cols * rows;
  // every cell is enqueued at most once ⇒ exact capacity
  return distancesFrom(tiles, width, cols, rows, fromCell, new Int32Array(nCells), new Int32Array(nCells));
}

/**
 * Fill `dist` with the BFS distance (in cells) of every cell from `fromCell`, -1 for unreachable.
 * @param {Uint8Array} tiles
 * @param {number} width
 * @param {number} cols
 * @param {number} rows
 * @param {number} fromCell
 * @param {Int32Array} dist   cols*rows slots, overwritten
 * @param {Int32Array} queue  cols*rows slots of scratch
 * @returns {number} cell index of the first cell discovered at the maximum distance
 */
function distancesFrom(tiles, width, cols, rows, fromCell, dist, queue) {
  dist.fill(-1);
  let head = 0;
  let tail = 0;
  dist[fromCell] = 0;
  queue[tail++] = fromCell;

  let best = fromCell;
  let bestDist = 0;

  while (head < tail) {
    const cell = queue[head++];
    const cx = cell % cols;
    const cy = (cell - cx) / cols;
    const nd = dist[cell] + 1;
    const tx = cx * 2 + 1;
    const ty = cy * 2 + 1;
    for (let d = 0; d < DIR_COUNT; d++) {
      const nx = cx + DIR_DX[d];
      const ny = cy + DIR_DY[d];
      if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
      if (tiles[(ty + DIR_DY[d]) * width + (tx + DIR_DX[d])] !== TILE.FLOOR) continue;
      const nCell = ny * cols + nx;
      if (dist[nCell] >= 0) continue;
      dist[nCell] = nd;
      queue[tail++] = nCell;
      if (nd > bestDist) {
        bestDist = nd;
        best = nCell;
      }
    }
  }
  return best;
}
